import 'package:flutter/material.dart';

/// Resolves a string identifier to its corresponding Material Icons IconData.
IconData resolveIcon(String name) {
  switch (name) {
    // Navigation & Actions
    case 'home':
      return Icons.home;
    case 'settings':
      return Icons.settings;
    case 'search':
      return Icons.search;
    case 'notifications':
      return Icons.notifications;
    case 'notifications_outlined':
      return Icons.notifications_none;
    case 'menu':
      return Icons.menu;
    case 'more_vert':
      return Icons.more_vert;
    case 'more_horiz':
      return Icons.more_horiz;
    case 'close':
      return Icons.close;
    case 'add':
      return Icons.add;
    case 'remove':
      return Icons.remove;
    case 'check':
      return Icons.check;
    case 'check_circle':
      return Icons.check_circle;
    case 'check_circle_outline':
      return Icons.check_circle_outline;
    case 'cancel':
      return Icons.cancel;
    case 'arrow_back':
      return Icons.arrow_back;
    case 'arrow_forward':
      return Icons.arrow_forward;
    case 'arrow_upward':
      return Icons.arrow_upward;
    case 'arrow_downward':
      return Icons.arrow_downward;
    case 'arrow_drop_down':
      return Icons.arrow_drop_down;
    case 'arrow_drop_up':
      return Icons.arrow_drop_up;
    case 'chevron_left':
      return Icons.chevron_left;
    case 'chevron_right':
      return Icons.chevron_right;
    case 'expand_more':
      return Icons.expand_more;
    case 'expand_less':
      return Icons.expand_less;
    case 'refresh':
      return Icons.refresh;
    case 'filter_list':
      return Icons.filter_list;
    case 'sort':
      return Icons.sort;
    case 'edit':
      return Icons.edit;
    case 'delete':
      return Icons.delete;
    case 'delete_outline':
      return Icons.delete_outline;
    case 'share':
      return Icons.share;
    case 'share_outlined':
      return Icons.share_outlined;
    case 'download':
      return Icons.download;
    case 'upload':
      return Icons.upload;
    case 'visibility':
      return Icons.visibility;
    case 'visibility_off':
      return Icons.visibility_off;
    case 'help':
      return Icons.help;
    case 'help_outline':
      return Icons.help_outline;
    case 'info':
      return Icons.info;
    case 'info_outline':
      return Icons.info_outline;
    case 'warning':
      return Icons.warning;
    case 'error':
      return Icons.error;
    case 'error_outline':
      return Icons.error_outline;
    case 'lock':
      return Icons.lock;
    case 'lock_open':
      return Icons.lock_open;
    case 'open_in_new':
      return Icons.open_in_new;

    // Social & Communication
    case 'thumb_up':
      return Icons.thumb_up;
    case 'thumb_up_outlined':
      return Icons.thumb_up_outlined;
    case 'thumb_down':
      return Icons.thumb_down;
    case 'thumb_down_outlined':
      return Icons.thumb_down_outlined;
    case 'favorite':
      return Icons.favorite;
    case 'favorite_border':
      return Icons.favorite_border;
    case 'comment':
    case 'chat':
      return Icons.chat_bubble_outline;
    case 'chat_bubble':
      return Icons.chat_bubble;
    case 'send':
      return Icons.send;
    case 'email':
      return Icons.email;
    case 'email_outlined':
      return Icons.mail_outline;
    case 'phone':
      return Icons.phone;
    case 'person':
      return Icons.person;
    case 'person_outline':
      return Icons.person_outline;
    case 'people':
      return Icons.people;
    case 'public':
      return Icons.public;
    case 'star':
      return Icons.star;
    case 'star_border':
      return Icons.star_border;
    case 'star_half':
      return Icons.star_half;

    // E-commerce & Shopping
    case 'shopping_cart':
      return Icons.shopping_cart;
    case 'shopping_cart_outlined':
      return Icons.shopping_cart_outlined;
    case 'shopping_bag':
      return Icons.shopping_bag;
    case 'shopping_bag_outlined':
      return Icons.shopping_bag_outlined;
    case 'store':
    case 'storefront':
      return Icons.storefront;
    case 'payment':
      return Icons.payment;
    case 'credit_card':
      return Icons.credit_card;
    case 'receipt':
      return Icons.receipt;
    case 'sell':
      return Icons.sell;
    case 'local_shipping':
      return Icons.local_shipping;
    case 'account_balance_wallet':
      return Icons.account_balance_wallet;
    case 'savings':
      return Icons.savings;

    // Media & Content
    case 'image':
    case 'photo':
      return Icons.photo_outlined;
    case 'camera_alt':
      return Icons.camera_alt;
    case 'video_library':
      return Icons.video_library;
    case 'play_arrow':
      return Icons.play_arrow;
    case 'pause':
      return Icons.pause;
    case 'stop':
      return Icons.stop;
    case 'skip_next':
      return Icons.skip_next;
    case 'skip_previous':
      return Icons.skip_previous;
    case 'volume_up':
      return Icons.volume_up;
    case 'volume_off':
      return Icons.volume_off;
    case 'mic':
      return Icons.mic;
    case 'music_note':
      return Icons.music_note;
    case 'grid_view':
      return Icons.grid_view;
    case 'list':
      return Icons.list;
    case 'article':
      return Icons.article;
    case 'description':
      return Icons.description;

    // Weather & Nature
    case 'wb_sunny':
      return Icons.wb_sunny;
    case 'cloud':
      return Icons.cloud;
    case 'thunderstorm':
      return Icons.thunderstorm;
    case 'water_drop':
      return Icons.water_drop;
    case 'ac_unit':
      return Icons.ac_unit;
    case 'air':
      return Icons.air;

    // Places & Devices
    case 'location_on':
      return Icons.location_on;
    case 'map':
      return Icons.map;
    case 'computer':
      return Icons.computer;
    case 'smartphone':
      return Icons.smartphone;
    case 'tablet':
      return Icons.tablet;
    case 'headphones':
      return Icons.headphones;
    case 'watch':
      return Icons.watch;
    case 'wifi':
      return Icons.wifi;
    case 'battery_full':
      return Icons.battery_full;

    default:
      return Icons.circle;
  }
}
