name: local_auth
package: local_auth
constraint: ^2.3.0
files: [shim.dart]
registers: [local_auth]
python_module: afik.plugins.local_auth
android:
  permissions: [biometrics]
  main_activity_base: FlutterFragmentActivity
  launch_theme_parent: "@style/Theme.AppCompat.DayNight.NoActionBar"
ios:
  permissions: [face_id]
