name: video_player
package: video_player
constraint: ^2.9.0
files: [shim.dart]
registers: [video_player]
widgets: [VideoPlayer]
python_module: pyflutter.plugins.video_player
android:
  permissions: [internet]
