name: connectivity_plus
package: connectivity_plus
constraint: ^7.0.0
files: [shim.dart]
registers: [connectivity, connectivity_plus]
python_module: afik.plugins.connectivity_plus
android:
  permissions: [network_state]
