"""
PyFlutter native plugins package.
"""

from __future__ import annotations

from pyflutter.plugins import (
    audioplayer,
    audioplayers,
    camera,
    chewie,
    connectivity,
    connectivity_plus,
    device_info,
    device_info_plus,
    file_picker,
    flutter_local_notifications,
    flutter_pdfview,
    flutter_secure_storage,
    hive,
    image_picker,
    local_auth,
    local_notifications,
    path_provider,
    pdf,
    pdfx,
    permission_handler,
    printing,
    secure_storage,
    share,
    share_plus,
    shared_preferences,
    sqflite,
    storage,
    syncfusion_flutter_pdfviewer,
    syncfusion_pdfviewer,
    url_launcher,
    video_player,
    webview,
    webview_flutter,
)
from pyflutter.plugins.manager import (
    add_flutter_package,
    call_plugin,
    handle_plugin_response,
    invoke_plugin_method,
)

__all__ = [
    "url_launcher",
    "storage",
    "shared_preferences",
    "path_provider",
    "device_info",
    "device_info_plus",
    "file_picker",
    "image_picker",
    "camera",
    "connectivity",
    "connectivity_plus",
    "audioplayer",
    "audioplayers",
    "video_player",
    "share",
    "share_plus",
    "webview",
    "webview_flutter",
    "chewie",
    "hive",
    "sqflite",
    "local_notifications",
    "flutter_local_notifications",
    "permission_handler",
    "secure_storage",
    "flutter_secure_storage",
    "local_auth",
    "pdf",
    "syncfusion_pdfviewer",
    "syncfusion_flutter_pdfviewer",
    "pdfx",
    "printing",
    "flutter_pdfview",
    "add_flutter_package",
    "invoke_plugin_method",
    "call_plugin",
    "handle_plugin_response",
]
