"""
PyFlutter plugin catalog.

PyFlutter does not bundle every Flutter package. Each supported package has an
entry in ``dart_runtime/plugin_catalog/<name>/`` made of a ``plugin.yaml`` (which
package and version, which native settings) and the hand-written Dart shim(s) that
call the real package API. A project lists the plugins it uses under ``plugins:``
in ``pyflutter.yaml`` and :func:`sync_plugins` makes the Flutter runtime match that
list:

* the Flutter dependencies are written to ``pubspec.yaml`` (managed block),
* the shims are copied to ``lib/plugins/installed/<name>/``,
* ``lib/plugins/installed_plugins.dart`` is regenerated so the shims register themselves,
* the native Android settings the plugins need are applied (activity base class,
  launch theme, minSdk, core library desugaring).

Everything here is idempotent: running it twice produces the same files, and removing a
plugin removes everything it added.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Optional

from pyflutter.core.logger import logger

try:
    import yaml
except ImportError:  # pragma: no cover - yaml is a declared dependency
    yaml = None

PUBSPEC_BEGIN = "  # pyflutter:plugins:begin (generated, do not edit)"
PUBSPEC_END = "  # pyflutter:plugins:end"
REGISTRANT_RELATIVE = Path("lib") / "plugins" / "installed_plugins.dart"
INSTALLED_RELATIVE = Path("lib") / "plugins" / "installed"

EMPTY_REGISTRANT = (
    "// GENERATED by `pyflutter add` / `pyflutter remove` / `pyflutter run`.\n"
    "// Do not edit by hand: the plugins listed in pyflutter.yaml are registered here.\n"
    "void registerInstalledPlugins() {}\n"
)

DEFAULT_LAUNCH_THEME = {
    "values": "@android:style/Theme.Light.NoTitleBar",
    "values-night": "@android:style/Theme.Black.NoTitleBar",
}


class CatalogError(Exception):
    """A plugin is unknown or its catalog entry is invalid."""


@dataclass
class CatalogEntry:
    name: str
    package: str
    constraint: str
    directory: Path
    files: list[str] = field(default_factory=lambda: ["shim.dart"])
    extra_packages: dict[str, str] = field(default_factory=dict)
    requires: list[str] = field(default_factory=list)
    registers: list[str] = field(default_factory=list)
    widgets: list[str] = field(default_factory=list)
    python_module: str = ""
    android: dict[str, Any] = field(default_factory=dict)
    ios: dict[str, Any] = field(default_factory=dict)
    notes: str = ""

    @property
    def dart_packages(self) -> dict[str, str]:
        """Every pub.dev dependency this plugin needs (name -> constraint)."""
        deps = {self.package: self.constraint}
        deps.update(self.extra_packages)
        return deps


# --------------------------------------------------------------------------- catalog


def catalog_dir(runtime_dir: Path) -> Path:
    return Path(runtime_dir) / "plugin_catalog"


def load_entry(directory: Path) -> CatalogEntry:
    """Reads one ``plugin.yaml``."""
    if yaml is None:
        raise CatalogError("PyYAML is required to read the plugin catalog.")
    meta_path = directory / "plugin.yaml"
    try:
        data = yaml.safe_load(meta_path.read_text(encoding="utf-8")) or {}
    except Exception as e:
        raise CatalogError(f"Cannot read {meta_path}: {e}") from e
    if not isinstance(data, dict) or "package" not in data:
        raise CatalogError(f"{meta_path} must define at least `package`.")
    name = str(data.get("name") or directory.name)
    return CatalogEntry(
        name=name,
        package=str(data["package"]),
        constraint=str(data.get("constraint", "any")),
        directory=directory,
        files=[str(f) for f in data.get("files", ["shim.dart"])],
        extra_packages={str(k): str(v) for k, v in (data.get("extra_packages") or {}).items()},
        requires=[str(r) for r in data.get("requires", [])],
        registers=[str(r) for r in data.get("registers", [])],
        widgets=[str(w) for w in data.get("widgets", [])],
        python_module=str(data.get("python_module", "")),
        android=dict(data.get("android") or {}),
        ios=dict(data.get("ios") or {}),
        notes=str(data.get("notes", "")).strip(),
    )


def load_catalog(runtime_dir: Path) -> dict[str, CatalogEntry]:
    """All catalog entries, keyed by plugin name."""
    root = catalog_dir(runtime_dir)
    entries: dict[str, CatalogEntry] = {}
    if not root.is_dir():
        return entries
    for sub in sorted(p for p in root.iterdir() if p.is_dir() and (p / "plugin.yaml").exists()):
        entry = load_entry(sub)
        entries[entry.name] = entry
    return entries


def expand_requirements(names: Iterable[str], catalog: dict[str, CatalogEntry]) -> list[CatalogEntry]:
    """Entries for ``names`` plus everything they require, dependencies first, no duplicates."""
    ordered: list[CatalogEntry] = []
    seen: set[str] = set()

    def visit(name: str, trail: tuple[str, ...]) -> None:
        if name in seen:
            return
        if name not in catalog:
            raise CatalogError(f"Unknown plugin '{name}'. Run `pyflutter plugin list` to see the catalog.")
        if name in trail:
            raise CatalogError(f"Circular plugin requirement: {' -> '.join(trail + (name,))}")
        for req in catalog[name].requires:
            visit(req, trail + (name,))
        seen.add(name)
        ordered.append(catalog[name])

    for n in names:
        visit(n, ())
    return ordered


# --------------------------------------------------------------------------- rendering


def render_registrant(entries: Iterable[CatalogEntry]) -> str:
    """Text of ``lib/plugins/installed_plugins.dart`` for the installed plugins."""
    entries = list(entries)
    if not entries:
        return EMPTY_REGISTRANT
    lines = [
        "// GENERATED by `pyflutter add` / `pyflutter remove` / `pyflutter run`.",
        "// Do not edit by hand: the plugins listed in pyflutter.yaml are registered here.",
    ]
    for e in entries:
        lines.append(f"import 'installed/{e.name}/{e.files[0]}' as plugin_{e.name};")
    lines += ["", "void registerInstalledPlugins() {"]
    for e in entries:
        lines.append(f"  plugin_{e.name}.register();")
    lines += ["}", ""]
    return "\n".join(lines)


def _dependencies_block_span(lines: list[str]) -> tuple[int, int]:
    """(start, end) line indexes of the top-level ``dependencies:`` mapping.

    ``end`` is the index just after the last non-blank line of the block, so inserted lines
    stay attached to the block and not to the following section.
    """
    start = next((i for i, line in enumerate(lines) if re.match(r"^dependencies:\s*(#.*)?$", line)), None)
    if start is None:
        raise CatalogError("pubspec.yaml has no `dependencies:` section.")
    end = len(lines)
    for i in range(start + 1, len(lines)):
        if lines[i].strip() and not lines[i].startswith((" ", "\t")):
            end = i
            break
    while end > start + 1 and not lines[end - 1].strip():
        end -= 1
    return start, end


def _yaml_scalar(value: str) -> str:
    """A pubspec version constraint, quoted when YAML would misread it (ranges start with > or <)."""
    if re.fullmatch(r"\^?[0-9A-Za-z.+\-]+|any", value):
        return value
    return "'" + value.replace("'", "''") + "'"


def render_pubspec(text: str, dependencies: dict[str, str]) -> str:
    """Returns ``text`` with the managed plugin block replaced by ``dependencies``."""
    lines = text.splitlines()
    # 1. drop the previous managed block
    if PUBSPEC_BEGIN in lines:
        b = lines.index(PUBSPEC_BEGIN)
        e = lines.index(PUBSPEC_END, b) if PUBSPEC_END in lines[b:] else b
        del lines[b : e + 1]
    # 2. insert the new one at the end of `dependencies:`
    if dependencies:
        start, end = _dependencies_block_span(lines)
        block = [PUBSPEC_BEGIN]
        block += [f"  {pkg}: {_yaml_scalar(constraint)}" for pkg, constraint in sorted(dependencies.items())]
        block.append(PUBSPEC_END)
        lines[end:end] = block
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- Android native settings


def _write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def apply_android_settings(runtime_dir: Path, entries: Iterable[CatalogEntry]) -> list[str]:
    """Applies the native Android settings the installed plugins ask for.

    Returns the names of the files that were modified. Each setting reverts to the Flutter
    default as soon as no installed plugin needs it.
    """
    entries = list(entries)
    changed: list[str] = []
    android = Path(runtime_dir) / "android" / "app"
    if not android.is_dir():
        return changed

    # --- MainActivity base class
    wants_fragment = any(e.android.get("main_activity_base") == "FlutterFragmentActivity" for e in entries)
    base = "FlutterFragmentActivity" if wants_fragment else "FlutterActivity"
    for activity in (android / "src" / "main" / "kotlin").rglob("MainActivity.kt"):
        text = activity.read_text(encoding="utf-8")
        new = re.sub(r"io\.flutter\.embedding\.android\.Flutter(Fragment)?Activity", f"io.flutter.embedding.android.{base}", text)
        new = re.sub(r":\s*Flutter(Fragment)?Activity\(\)", f": {base}()", new)
        if _write_if_changed(activity, new):
            changed.append(str(activity))

    # --- launch theme parent
    wanted_theme = next((e.android["launch_theme_parent"] for e in entries if e.android.get("launch_theme_parent")), None)
    for variant, default in DEFAULT_LAUNCH_THEME.items():
        styles = android / "src" / "main" / "res" / variant / "styles.xml"
        if not styles.exists():
            continue
        text = styles.read_text(encoding="utf-8")
        parent = wanted_theme or default
        new = re.sub(r'(<style name="LaunchTheme" parent=")[^"]*(")', lambda m: f"{m.group(1)}{parent}{m.group(2)}", text)
        if _write_if_changed(styles, new):
            changed.append(str(styles))

    # --- Gradle: minSdk and core library desugaring
    gradle = android / "build.gradle.kts"
    if gradle.exists():
        text = gradle.read_text(encoding="utf-8")
        min_sdk = max((int(e.android.get("min_sdk", 0)) for e in entries), default=0)
        min_line = f"minSdk = maxOf(flutter.minSdkVersion, {min_sdk})" if min_sdk else "minSdk = flutter.minSdkVersion"
        new = re.sub(r"minSdk = (maxOf\(flutter\.minSdkVersion, \d+\)|flutter\.minSdkVersion)", min_line, text)

        wants_desugar = any(e.android.get("desugaring") for e in entries)
        marker_opt = "        isCoreLibraryDesugaringEnabled = true // pyflutter:desugaring\n"
        new = new.replace(marker_opt, "")
        new = re.sub(r"\n// pyflutter:desugaring:begin.*?// pyflutter:desugaring:end\n", "", new, flags=re.S)
        if wants_desugar:
            new = new.replace("    compileOptions {\n", "    compileOptions {\n" + marker_opt, 1)
            new = new.rstrip("\n") + "\n" + (
                "\n// pyflutter:desugaring:begin\n"
                "dependencies {\n"
                '    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")\n'
                "}\n"
                "// pyflutter:desugaring:end\n"
            )
        if _write_if_changed(gradle, new):
            changed.append(str(gradle))
    return changed


# --------------------------------------------------------------------------- sync


@dataclass
class SyncResult:
    plugins: list[str] = field(default_factory=list)
    pubspec_changed: bool = False
    files_changed: list[str] = field(default_factory=list)
    pub_get_ran: bool = False


def plugin_permissions(entries: Iterable[CatalogEntry]) -> list[str]:
    """Permission keys (see manifest_sync) required by the installed plugins."""
    perms: list[str] = []
    for e in entries:
        for source in (e.android, e.ios):
            for p in source.get("permissions", []) or []:
                if p not in perms:
                    perms.append(p)
    return perms


def plugin_queries(entries: Iterable[CatalogEntry]) -> list[str]:
    """Android <queries> snippets (package visibility) required by the installed plugins."""
    snippets: list[str] = []
    for e in entries:
        for snippet in e.android.get("queries", []) or []:
            if snippet not in snippets:
                snippets.append(str(snippet))
    return snippets


def sync_plugins(
    runtime_dir: Path,
    wanted: Iterable[str],
    *,
    run_pub_get: bool = True,
    template_dir: Optional[Path] = None,
    extra_dependencies: Optional[dict[str, str]] = None,
) -> SyncResult:
    """Makes the Flutter runtime in ``runtime_dir`` match the ``wanted`` plugin names.

    ``template_dir`` is where the catalog lives (the framework's ``dart_runtime``); it defaults
    to ``runtime_dir`` itself. ``extra_dependencies`` are Flutter packages declared by the project
    that have no catalog entry (name -> version constraint).
    """
    runtime_dir = Path(runtime_dir)
    catalog = load_catalog(Path(template_dir) if template_dir else runtime_dir)
    entries = expand_requirements(list(dict.fromkeys(wanted)), catalog)
    result = SyncResult(plugins=[e.name for e in entries])

    # 1. pubspec.yaml
    deps: dict[str, str] = {}
    for name, constraint in (extra_dependencies or {}).items():
        deps[name] = constraint
    for e in entries:
        deps.update(e.dart_packages)
    pubspec = runtime_dir / "pubspec.yaml"
    new_pubspec = render_pubspec(pubspec.read_text(encoding="utf-8"), deps)
    if _write_if_changed(pubspec, new_pubspec):
        result.pubspec_changed = True
        result.files_changed.append(str(pubspec))

    # 2. shims
    installed_root = runtime_dir / INSTALLED_RELATIVE
    installed_root.mkdir(parents=True, exist_ok=True)
    keep = {e.name for e in entries}
    for stale in [p for p in installed_root.iterdir() if p.is_dir() and p.name not in keep]:
        shutil.rmtree(stale)
        result.files_changed.append(str(stale))
    for e in entries:
        target = installed_root / e.name
        target.mkdir(exist_ok=True)
        for rel in e.files:
            source = (e.directory / rel).read_text(encoding="utf-8")
            if _write_if_changed(target / rel, source):
                result.files_changed.append(str(target / rel))

    # 3. registrant
    registrant = runtime_dir / REGISTRANT_RELATIVE
    if _write_if_changed(registrant, render_registrant(entries)):
        result.files_changed.append(str(registrant))

    # 4. native settings
    result.files_changed += apply_android_settings(runtime_dir, entries)

    # 5. resolve packages
    if run_pub_get and result.pubspec_changed:
        flutter_bin = shutil.which("flutter") or shutil.which("flutter.bat")
        if flutter_bin:
            try:
                subprocess.run([flutter_bin, "pub", "get"], cwd=str(runtime_dir), check=True,
                               capture_output=True, text=True)
                result.pub_get_ran = True
            except subprocess.CalledProcessError as e:
                logger.error("flutter pub get failed:\n{}", (e.stdout or "") + (e.stderr or ""))
                raise CatalogError("flutter pub get failed; see the log above.") from e
        else:
            logger.warning("Flutter SDK not found: run `flutter pub get` in {} before building.", runtime_dir)

    for note in [e.notes for e in entries if e.notes]:
        logger.info("Plugin note: {}", note)
    return result


# --------------------------------------------------------------------------- scaffolding

SHIM_TEMPLATE = """import 'dart:async';

import 'package:pyflutter_dart_runtime/plugins/plugin_registry.dart';
// TODO: import 'package:{package}/{package}.dart';

/// Dispatch shim for `{package}`.
///
/// Read the package documentation, then map each Dart method you want to expose to a `case`
/// below. Rules: return only what the platform answered (never invent a successful result),
/// throw for anything unsupported, keep results simple (Map / List / String / bool / null).
class {class_name}Shim implements PyFlutterPlugin {{
  @override
  Future<dynamic> handleMethodCall(String method, Map<String, String> args) async {{
    switch (method) {{
      // case 'someMethod':
      //   final value = await SomeClass().someMethod(args['name'] ?? '');
      //   return {{'result': value}};
      default:
        throw UnsupportedError('{package} method "$method" is not supported.');
    }}
  }}
}}

/// Called by the generated installed_plugins.dart.
void register() {{
  PluginRegistry.register('{name}', {class_name}Shim());
}}
"""

PY_TEMPLATE = '''"""
PyFlutter {name} plugin (matches pub.dev package: {package}).
"""

from __future__ import annotations

from pyflutter.plugins.manager import call_plugin


# One Dart method = one snake_case Python method. A missing or malformed answer must
# read as a failure, never as a success.
def example() -> bool:
    """TODO: replace with the first mapped method."""
    res = call_plugin("{name}", "someMethod", {{}})
    return isinstance(res, dict) and res.get("result") is True
'''

TEST_TEMPLATE = '''"""Tests for the {name} plugin mapping."""

import unittest
from unittest.mock import patch

from pyflutter.plugins import {name}


class Test{class_name}(unittest.TestCase):
    def test_missing_or_malformed_answer_is_a_failure(self):
        for answer in (None, {{}}, "ok", []):
            with patch.object({name}, "call_plugin", return_value=answer):
                self.assertFalse({name}.example())


if __name__ == "__main__":
    unittest.main()
'''


def _class_name(name: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[_\-]", name))


def scaffold_plugin(name: str, runtime_dir: Path, py_framework_dir: Path, constraint: str = "any") -> list[Path]:
    """Creates the skeleton to map a new package (catalog entry, shim, Python module, test)."""
    if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
        raise CatalogError(f"'{name}' is not a valid package name (lowercase letters, digits, underscores).")
    directory = catalog_dir(runtime_dir) / name
    if directory.exists():
        raise CatalogError(f"{directory} already exists.")
    directory.mkdir(parents=True)
    cls = _class_name(name)
    created = []
    (directory / "plugin.yaml").write_text(
        f"name: {name}\npackage: {name}\nconstraint: {constraint}\nshim: shim.dart\nfiles: [shim.dart]\n"
        f"registers: [{name}]\npython_module: pyflutter.plugins.{name}\n"
        "# android: {permissions: [], min_sdk: 0}\n# ios: {permissions: []}\n",
        encoding="utf-8",
    )
    created.append(directory / "plugin.yaml")
    (directory / "shim.dart").write_text(SHIM_TEMPLATE.format(package=name, name=name, class_name=cls), encoding="utf-8")
    created.append(directory / "shim.dart")
    py_file = py_framework_dir / "pyflutter" / "plugins" / f"{name}.py"
    if not py_file.exists():
        py_file.write_text(PY_TEMPLATE.format(name=name, package=name), encoding="utf-8")
        created.append(py_file)
    test_file = py_framework_dir / "tests" / f"test_plugin_{name}.py"
    if not test_file.exists():
        test_file.write_text(TEST_TEMPLATE.format(name=name, class_name=cls), encoding="utf-8")
        created.append(test_file)
    return created


# --------------------------------------------------------------------------- project level


def prepare_runtime(runtime: Any, config: Any, *, run_pub_get: bool = True) -> SyncResult:
    """Brings the project's Flutter runtime in line with ``pyflutter.yaml`` before `run` / `build`.

    ``runtime`` is a :class:`~pyflutter.core.runtime_project.ProjectRuntime`. It creates or
    refreshes the project copy of the runtime, installs the plugins and extra Flutter packages
    listed in ``config``, and writes the permissions (the ones of ``pyflutter.yaml`` plus the ones
    the plugins need) into the Android manifest and the iOS plist.
    """
    from pyflutter.cli.manifest_sync import sync_platform_metadata

    runtime.ensure()
    catalog = load_catalog(runtime.template_dir)
    catalog_packages = {e.package for e in catalog.values()}
    extras = {n: c for n, c in config.flutter_dependencies.items() if n not in catalog_packages}
    result = sync_plugins(
        runtime.runtime_dir, config.plugins,
        run_pub_get=run_pub_get, template_dir=runtime.template_dir, extra_dependencies=extras,
    )
    entries = expand_requirements(config.plugins, catalog)
    sync_platform_metadata(
        runtime.runtime_dir, config,
        extra_permissions=plugin_permissions(entries), extra_queries=plugin_queries(entries),
    )
    if result.files_changed:
        logger.info("Plugins synced: {}", ", ".join(result.plugins) or "(none)")
    return result


def resolved_version(runtime_dir: Path, package: str) -> Optional[str]:
    """The version `flutter pub get` locked for ``package`` in ``pubspec.lock`` (None if unknown)."""
    lock = Path(runtime_dir) / "pubspec.lock"
    if yaml is None or not lock.exists():
        return None
    try:
        data = yaml.safe_load(lock.read_text(encoding="utf-8")) or {}
        return str(data["packages"][package]["version"])
    except (KeyError, TypeError, ValueError):
        return None
